import { z } from "zod";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { SSEClientTransport } from "@modelcontextprotocol/sdk/client/sse.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { HydraTool } from "./types.js";

// --- Server state types ---
export type McpServerState = 'connecting' | 'connected' | 'failed' | 'timeout' | 'disconnected';

export interface McpServerStatus {
  name: string;
  state: McpServerState;
  toolCount: number;
  error?: string;
  connectedAt?: string;
  transport: 'stdio' | 'sse' | 'http' | 'unknown';
}

// --- Improved JSON Schema → Zod conversion ---
function jsonSchemaToZod(jsonSchema: any): z.ZodType<any> {
  if (!jsonSchema || typeof jsonSchema !== 'object') return z.string();

  // Handle root-level non-object schemas
  if (jsonSchema.type && jsonSchema.type !== 'object' && !jsonSchema.properties) {
    return convertType(jsonSchema, []);
  }

  if (!jsonSchema.properties && jsonSchema.type !== 'object') return z.string();

  const properties = jsonSchema.properties || {};
  const required = jsonSchema.required || [];
  const shape: Record<string, z.ZodType<any>> = {};

  for (const [key, val] of Object.entries<any>(properties)) {
    shape[key] = convertType(val, required, key);
  }
  return z.object(shape);
}

function convertType(val: any, required: string[], key?: string): z.ZodType<any> {
  let zType: any = z.string();

  if (val.enum && Array.isArray(val.enum)) {
    // Enum support
    if (val.enum.length === 1) {
      zType = z.literal(val.enum[0]);
    } else {
      zType = z.enum(val.enum as [string, ...string[]]);
    }
  } else if (val.type === 'string') {
    zType = z.string();
  } else if (val.type === 'number' || val.type === 'integer') {
    zType = z.number();
  } else if (val.type === 'boolean') {
    zType = z.boolean();
  } else if (val.type === 'array') {
    if (val.items) {
      zType = z.array(convertType(val.items, []));
    } else {
      zType = z.array(z.string());
    }
  } else if (val.type === 'object') {
    // Nested object support
    if (val.properties) {
      zType = jsonSchemaToZod(val);
    } else {
      zType = z.record(z.string());
    }
  } else if (val.oneOf || val.anyOf) {
    // Local LLMs parser (llama.cpp) crashes with "Cannot determine type of item" on anyOf schemas.
    // We fall back to string as the safest universal primitive.
    zType = z.string();
  }

  // Nullable support: LLMs (like Mistral API) reject 'anyOf' which is generated by .nullable().
  // Using .optional() instead is a safer pattern for function calling.
  if (val.nullable === true) {
    zType = zType.optional();
  }

  if (val.description) {
    zType = zType.describe(val.description);
  }

  if (key && !required.includes(key)) {
    zType = zType.optional();
  }

  return zType;
}

// --- Timeout utility ---
const DEFAULT_CONNECT_TIMEOUT_MS = 10_000;

async function withTimeout<T>(promise: Promise<T>, timeoutMs: number, name: string): Promise<T> {
  let timeoutHandle: any;
  const timeoutPromise = new Promise<T>((_, reject) => {
    timeoutHandle = setTimeout(() => reject(new Error(`Timeout de ${timeoutMs}ms agotado para ${name}`)), timeoutMs);
  });
  return Promise.race([promise, timeoutPromise]).finally(() => clearTimeout(timeoutHandle));
}

// --- Kill transport helper ---
function killTransport(transport: any): void {
  if (!transport) return;
  try { transport.close?.(); } catch (_) {}
  try { transport.kill?.(); } catch (_) {}
  try { transport._process?.kill?.(); } catch (_) {}
  try { transport.process?.kill?.(); } catch (_) {}
}

// --- Tool-result sanitisation ---
// Overall cap on the text an MCP result injects into the model's context.
// Without it, a Playwright screenshot (an `image` part with base64) or a full
// DOM snapshot got dumped raw (100k+ tokens) and overflowed the context window
// of local models, wrecking the response. Mirrors fetch_url's MAX_OUTPUT, with
// a bit more headroom for legitimate text.
const MAX_MCP_OUTPUT = 8_000;

// Estimates the size (KB) of a non-text part's original payload for the marker,
// without dumping its content. Base64 ≈ 3/4 of the real bytes.
function partSizeKB(part: any): number {
  const raw = part?.data ?? part?.blob ?? "";
  const len = typeof raw === "string" ? raw.length : 0;
  return Math.max(1, Math.round((len * 0.75) / 1024));
}

// Turns an MCP result's `content` array into text that is safe for the context:
// text is kept; images/audio/blobs are replaced by a marker with their size
// (never their base64); resources and the rest are serialised and truncated.
// The total is capped to MAX_MCP_OUTPUT.
function sanitizeMcpContent(content: any[], toolName: string): string {
  const parts: string[] = (Array.isArray(content) ? content : []).map((c: any) => {
    if (c && typeof c.text === "string") return c.text;
    const type = c?.type;
    if (type === "image" || type === "audio") {
      const mime = c?.mimeType || type;
      return `[${type} ${mime} omitted: ~${partSizeKB(c)} KB — not embeddable in text context]`;
    }
    if (type === "resource" && c?.resource) {
      const r = c.resource;
      if (typeof r.text === "string") return r.text;
      return `[resource ${r.mimeType || ""} ${r.uri || ""} omitted: ~${partSizeKB(r)} KB]`;
    }
    // Unknown part: serialise but bounded, so we don't dump huge blobs.
    const s = JSON.stringify(c);
    return s.length > 1_000 ? s.slice(0, 1_000) + `…[${type || "?"} part truncated]` : s;
  });

  let out = parts.join("\n");
  if (out.length > MAX_MCP_OUTPUT) {
    const omitted = out.length - MAX_MCP_OUTPUT;
    console.warn(`[MCP Tool Exec] ${toolName} result truncated: ${omitted} chars omitted (cap ${MAX_MCP_OUTPUT}).`);
    out = out.slice(0, MAX_MCP_OUTPUT) + `\n…[result truncated, ${omitted} chars omitted]`;
  }
  return out;
}

// --- Main MCP Client Manager ---
export class McpClientManager {
  private clients = new Map<string, Client>();
  private transports = new Map<string, any>();
  public mcpTools = new Map<string, HydraTool>();

  // Per-server state tracking
  private serverStatuses = new Map<string, McpServerStatus>();

  // Store original config per server for reconnection
  private serverConfigs = new Map<string, any>();

  async connectServers(mcpConfig: any) {
    if (!mcpConfig || !mcpConfig.mcpServers) return;
    const PER_SERVER_TIMEOUT_MS = 10_000;

    const connectionPromises = Object.entries<any>(mcpConfig.mcpServers).map(async ([serverName, config]) => {
      if (config.switch === "off") {
        console.log(`[MCP] Skipping disabled server: ${serverName}`);
        this.serverStatuses.set(serverName, {
          name: serverName,
          state: 'disconnected',
          toolCount: 0,
          transport: config.command ? 'stdio' : config.url ? 'sse' : 'unknown'
        });
        return;
      }

      // Store config for potential reconnection
      this.serverConfigs.set(serverName, config);

      // Mark as connecting
      this.serverStatuses.set(serverName, {
        name: serverName,
        state: 'connecting',
        toolCount: 0,
        transport: config.command ? 'stdio' : config.url ? 'sse' : 'unknown'
      });

      let transport: any = null;
      let transportKind: 'stdio' | 'sse' | 'http' = config.command ? 'stdio' : 'sse';
      try {
        await withTimeout((async () => {
          let client: Client;
          if (config.command) {
            console.log(`[MCP] Connecting to ${serverName} via STDIO (${config.command})...`);
            transport = new StdioClientTransport({
              command: config.command,
              args: config.args || [],
              env: { ...process.env, ...(config.env || {}) }
            });
            client = new Client({ name: "hydraops", version: "1.0.0" }, { capabilities: {} });
            await client.connect(transport);
          } else if (config.url) {
            // Remote servers: Streamable HTTP first (current spec), SSE as legacy fallback.
            // config.headers (e.g. Authorization) is forwarded on both transports.
            const httpOpts = config.headers ? { requestInit: { headers: config.headers } } : undefined;
            try {
              console.log(`[MCP] Connecting to ${serverName} via Streamable HTTP (${config.url})...`);
              transport = new StreamableHTTPClientTransport(new URL(config.url), httpOpts);
              client = new Client({ name: "hydraops", version: "1.0.0" }, { capabilities: {} });
              await client.connect(transport);
              transportKind = 'http';
            } catch (httpErr: any) {
              killTransport(transport);
              console.log(`[MCP] ${serverName}: Streamable HTTP failed (${httpErr?.message}) — falling back to SSE...`);
              transport = new SSEClientTransport(new URL(config.url), httpOpts as any);
              client = new Client({ name: "hydraops", version: "1.0.0" }, { capabilities: {} });
              await client.connect(transport);
              transportKind = 'sse';
            }
          } else {
            throw new Error(`Invalid configuration for ${serverName}: no command or url`);
          }

          this.clients.set(serverName, client);
          this.transports.set(serverName, transport);

          // Request tools from this MCP server
          const response: any = await client.request({ method: "tools/list" }, z.any());
          const tools = response?.tools || [];

          let registeredCount = 0;
          for (const t of tools) {
            const toolName = `${serverName.replace(/\s+/g, '_').toLowerCase()}_${t.name}`;
            const zodSchema = jsonSchemaToZod(t.inputSchema);

            this.mcpTools.set(toolName, {
              name: toolName,
              description: `[From ${serverName}]: ${t.description || ''}`,
              schema: zodSchema,
              execute: this.createToolExecutor(serverName, client, t.name)
            });
            registeredCount++;
            console.log(`[MCP] Registered tool: ${toolName}`);
          }

          // Mark as connected
          this.serverStatuses.set(serverName, {
            name: serverName,
            state: 'connected',
            toolCount: registeredCount,
            connectedAt: new Date().toISOString(),
            transport: transportKind
          });

          console.log(`[MCP] ✅ ${serverName} connected — ${registeredCount} tools registered.`);
        })(), PER_SERVER_TIMEOUT_MS, `connection to ${serverName}`);
      } catch (err: any) {
        const isTimeout = err.message?.includes('Timeout');
        const state: McpServerState = isTimeout ? 'timeout' : 'failed';
        const errorMsg = err.message || 'Unknown error';

        console.error(`[MCP] ❌ Server ${serverName} ${state}: ${errorMsg}`);

        this.serverStatuses.set(serverName, {
          name: serverName,
          state,
          toolCount: 0,
          error: errorMsg,
          transport: config.command ? 'stdio' : config.url ? 'sse' : 'unknown'
        });

        // Kill the transport/child process to prevent zombies
        killTransport(transport);

        // Also remove from clients/transports if they were partially set
        this.clients.delete(serverName);
        this.transports.delete(serverName);
      }
    });

    // FIXED: Actually wait for all connections to settle
    const results = await Promise.allSettled(connectionPromises);
    const connected = [...this.serverStatuses.values()].filter(s => s.state === 'connected').length;
    const failed = [...this.serverStatuses.values()].filter(s => s.state === 'failed' || s.state === 'timeout').length;
    const disabled = [...this.serverStatuses.values()].filter(s => s.state === 'disconnected').length;

    console.log(`[MCP] Initialization complete: ${connected} connected, ${failed} failed, ${disabled} disabled. Total tools: ${this.mcpTools.size}`);
  }

  /**
   * Creates a tool executor with automatic error handling and reconnection
   */
  private createToolExecutor(serverName: string, client: Client, toolOriginalName: string) {
    return async (args: any): Promise<string> => {
      console.log(`[MCP Tool Exec] Calling ${toolOriginalName} on ${serverName}...`);

      try {
        const res: any = await withTimeout(
          client.request(
            { method: "tools/call", params: { name: toolOriginalName, arguments: args } },
            z.any()
          ),
          30_000,
          `tool call ${toolOriginalName}`
        );

        if (res.isError) {
          return `MCP Server Error: ${sanitizeMcpContent(res.content, toolOriginalName)}`;
        }

        return sanitizeMcpContent(res.content, toolOriginalName);
      } catch (execErr: any) {
        const errMsg = execErr.message || 'Unknown execution error';
        console.error(`[MCP Tool Exec] ❌ ${toolOriginalName} on ${serverName} failed: ${errMsg}`);

        // Mark server as failed if connection is dead
        if (errMsg.includes('closed') || errMsg.includes('EPIPE') || errMsg.includes('killed') || errMsg.includes('disconnect')) {
          this.serverStatuses.set(serverName, {
            name: serverName,
            state: 'failed',
            toolCount: 0,
            error: `Connection lost: ${errMsg}`,
            transport: this.serverStatuses.get(serverName)?.transport || 'unknown'
          });

          // Attempt reconnection in background
          const config = this.serverConfigs.get(serverName);
          if (config) {
            console.log(`[MCP] Scheduling reconnection for ${serverName}...`);
            this.reconnectServer(serverName, config).catch(
              e => console.error(`[MCP] Reconnection for ${serverName} failed: ${e.message}`)
            );
          }
        }

        return `Error executing MCP tool ${toolOriginalName}: ${errMsg}`;
      }
    };
  }

  /**
   * Reconnect a single server that has disconnected
   */
  private async reconnectServer(serverName: string, config: any): Promise<void> {
    // Clean up old connection
    const oldTransport = this.transports.get(serverName);
    killTransport(oldTransport);
    const oldClient = this.clients.get(serverName);
    try { await oldClient?.close(); } catch (_) {}
    this.clients.delete(serverName);
    this.transports.delete(serverName);

    // Remove old tools from this server
    for (const [toolName] of this.mcpTools) {
      if (toolName.startsWith(`${serverName.replace(/\s+/g, '_').toLowerCase()}_`)) {
        this.mcpTools.delete(toolName);
      }
    }

    // Reconnect as if it were a fresh config (single server)
    await this.connectServers({ mcpServers: { [serverName]: config } });
  }

  /**
   * Get the statuses of all known MCP servers
   */
  getStatuses(): McpServerStatus[] {
    return [...this.serverStatuses.values()];
  }

  async closeAll() {
    // Close transports first to kill child processes
    for (const [name, transport] of this.transports.entries()) {
      try {
        await transport.close();
      } catch (e) {
        killTransport(transport);
        console.error(`[MCP] Error cerrando transporte ${name}`, e);
      }
    }
    this.transports.clear();

    for (const [name, client] of this.clients.entries()) {
      try {
        await client.close();
      } catch (e) {
        console.error(`[MCP] Error cerrando client ${name}`, e);
      }
    }
    this.clients.clear();
    this.mcpTools.clear();
    this.serverStatuses.clear();
    this.serverConfigs.clear();
  }
}
