import { z } from "zod";
import { keepToolImage, toolImageMarker } from './tool-images.js';
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { SSEClientTransport } from "@modelcontextprotocol/sdk/client/sse.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { HydraTool } from "./types.js";
import { classifyMcpTool } from "./provenance.js";
import { MIN_TOOL_TIMEOUT_SECONDS, MAX_TOOL_TIMEOUT_SECONDS } from "./presets.js";

// --- Server state types ---
export type McpServerState = 'connecting' | 'connected' | 'failed' | 'timeout' | 'disconnected';

export interface McpServerStatus {
  name: string;
  state: McpServerState;
  toolCount: number;
  /** Tools nobody classified (no toolRisk entry, known server or annotation): they ask for approval. */
  unclassified?: number;
  error?: string;
  connectedAt?: string;
  transport: 'stdio' | 'sse' | 'http' | 'unknown';
}

// --- Improved JSON Schema → Zod conversion ---
function jsonSchemaToZod(jsonSchema: any): z.ZodType<any> {
  if (!jsonSchema || typeof jsonSchema !== 'object') return z.string();

  // Handle root-level non-object schemas
  if (jsonSchema.type && jsonSchema.type !== 'object' && !jsonSchema.properties) {
    return convertType(jsonSchema, []);
  }

  if (!jsonSchema.properties && jsonSchema.type !== 'object') return z.string();

  const properties = jsonSchema.properties || {};
  const required = jsonSchema.required || [];
  const shape: Record<string, z.ZodType<any>> = {};

  for (const [key, val] of Object.entries<any>(properties)) {
    shape[key] = convertType(val, required, key);
  }
  return z.object(shape);
}

function convertType(val: any, required: string[], key?: string): z.ZodType<any> {
  let zType: any = z.string();

  if (val.enum && Array.isArray(val.enum)) {
    // Enum support
    if (val.enum.length === 1) {
      zType = z.literal(val.enum[0]);
    } else {
      zType = z.enum(val.enum as [string, ...string[]]);
    }
  } else if (val.type === 'string') {
    zType = z.string();
  } else if (val.type === 'number' || val.type === 'integer') {
    zType = z.number();
  } else if (val.type === 'boolean') {
    zType = z.boolean();
  } else if (val.type === 'array') {
    if (val.items) {
      zType = z.array(convertType(val.items, []));
    } else {
      zType = z.array(z.string());
    }
  } else if (val.type === 'object') {
    // Nested object support
    if (val.properties) {
      zType = jsonSchemaToZod(val);
    } else {
      zType = z.record(z.string());
    }
  } else if (val.oneOf || val.anyOf) {
    // Local LLMs parser (llama.cpp) crashes with "Cannot determine type of item" on anyOf schemas.
    // We fall back to string as the safest universal primitive.
    zType = z.string();
  }

  // Nullable support: LLMs (like Mistral API) reject 'anyOf' which is generated by .nullable().
  // Using .optional() instead is a safer pattern for function calling.
  if (val.nullable === true) {
    zType = zType.optional();
  }

  if (val.description) {
    zType = zType.describe(val.description);
  }

  if (key && !required.includes(key)) {
    zType = zType.optional();
  }

  return zType;
}

// --- Timeout utility ---
const DEFAULT_CONNECT_TIMEOUT_MS = 10_000;

/**
 * How long one tool call of a server may take: 30 seconds unless its entry in the MCP config
 * sets `toolTimeoutSeconds` (30 to 3600). A server whose tools wait on long work, such as a
 * generation that takes minutes, would otherwise have every such call cut short.
 */
export function toolCallTimeoutMs(config: any): number {
  const s = Number(config?.toolTimeoutSeconds);
  if (!Number.isFinite(s)) return MIN_TOOL_TIMEOUT_SECONDS * 1000;
  return Math.min(MAX_TOOL_TIMEOUT_SECONDS, Math.max(MIN_TOOL_TIMEOUT_SECONDS, Math.floor(s))) * 1000;
}

async function withTimeout<T>(promise: Promise<T>, timeoutMs: number, name: string): Promise<T> {
  let timeoutHandle: any;
  const timeoutPromise = new Promise<T>((_, reject) => {
    timeoutHandle = setTimeout(() => reject(new Error(`Timeout de ${timeoutMs}ms agotado para ${name}`)), timeoutMs);
  });
  return Promise.race([promise, timeoutPromise]).finally(() => clearTimeout(timeoutHandle));
}

// --- Kill transport helper ---
function killTransport(transport: any): void {
  if (!transport) return;
  try { transport.close?.(); } catch (_) {}
  try { transport.kill?.(); } catch (_) {}
  try { transport._process?.kill?.(); } catch (_) {}
  try { transport.process?.kill?.(); } catch (_) {}
}

// --- Tool-result sanitisation ---
// Overall cap on the text an MCP result can produce. A Playwright screenshot (an
// `image` part with base64) or a full DOM snapshot used to be dumped raw (100k+
// tokens) and overflow the context window of local models; images are replaced by
// markers below, and the text goes whole to the task vault, which hands the model a
// digest (see vault.ts). This only stops a runaway result.
const MAX_MCP_OUTPUT = 200_000;

// Estimates the size (KB) of a non-text part's original payload for the marker,
// without dumping its content. Base64 ≈ 3/4 of the real bytes.
function partSizeKB(part: any): number {
  const raw = part?.data ?? part?.blob ?? "";
  const len = typeof raw === "string" ? raw.length : 0;
  return Math.max(1, Math.round((len * 0.75) / 1024));
}

// Turns an MCP result's `content` array into text that is safe for the context:
// text is kept; images/audio/blobs are replaced by a marker with their size
// (never their base64); resources and the rest are serialised and truncated.
// The total is capped to MAX_MCP_OUTPUT.
function sanitizeMcpContent(content: any[], toolName: string): string {
  const parts: string[] = (Array.isArray(content) ? content : []).map((c: any) => {
    if (c && typeof c.text === "string") return c.text;
    const type = c?.type;
    if (type === "image" || type === "audio") {
      const mime = c?.mimeType || type;
      // A picture is kept aside and handed to a model that can see it (see tool-images.ts).
      const id = type === 'image' ? keepToolImage(mime, c?.data) : null;
      if (id) return toolImageMarker(id, String(mime).toLowerCase().split(';')[0].trim(), partSizeKB(c));
      return `[${type} ${mime} omitted: ~${partSizeKB(c)} KB — not embeddable in text context]`;
    }
    if (type === "resource" && c?.resource) {
      const r = c.resource;
      if (typeof r.text === "string") return r.text;
      return `[resource ${r.mimeType || ""} ${r.uri || ""} omitted: ~${partSizeKB(r)} KB]`;
    }
    // Unknown part: serialise but bounded, so we don't dump huge blobs.
    const s = JSON.stringify(c);
    return s.length > 1_000 ? s.slice(0, 1_000) + `…[${type || "?"} part truncated]` : s;
  });

  let out = parts.join("\n");
  if (out.length > MAX_MCP_OUTPUT) {
    const omitted = out.length - MAX_MCP_OUTPUT;
    console.warn(`[MCP Tool Exec] ${toolName} result truncated: ${omitted} chars omitted (cap ${MAX_MCP_OUTPUT}).`);
    out = out.slice(0, MAX_MCP_OUTPUT) + `\n…[result truncated, ${omitted} chars omitted]`;
  }
  return out;
}

// A server that did not connect is retried by the next task, not more often than this.
const RETRY_COOLDOWN_MS = 60_000;
// A server that reports a lost connection is restarted, not more often than this.
const RESTART_COOLDOWN_MS = 30_000;
// What a server says when the thing it drives is gone (checked on the start of a result).
const DOWNSTREAM_LOST = /\bnot connected\b|connection (?:refused|lost|closed|reset)|ECONNREFUSED|ECONNRESET/i;

/**
 * The part of an MCP config a set of agents can actually use: the servers their tools.md
 * lines name (the server itself, or one of its tools). A worker connects only these, so
 * a server no agent of its kind was given is not started there at all.
 */
export function filterMcpConfigForTools(configStr: string, toolLines: string[]): string {
  let parsed: any;
  try { parsed = JSON.parse(configStr); } catch { return '{"mcpServers":{}}'; }
  const norm = (v: string) => v.replace(/\s+/g, '_').toLowerCase();
  const lines = toolLines.map(norm).filter(Boolean);
  const kept: Record<string, unknown> = {};
  for (const [name, cfg] of Object.entries<any>(parsed?.mcpServers ?? {})) {
    const server = norm(name);
    if (lines.some((l) => l === server || l.startsWith(server + '_'))) kept[name] = cfg;
  }
  return JSON.stringify({ mcpServers: kept });
}

// --- Main MCP Client Manager ---
export class McpClientManager {
  // Cooldowns are parameters so the tests need not wait a minute.
  constructor(private readonly opts: { retryCooldownMs?: number; restartCooldownMs?: number } = {}) {}

  private clients = new Map<string, Client>();
  private transports = new Map<string, any>();
  public mcpTools = new Map<string, HydraTool>();

  // Per-server state tracking
  private serverStatuses = new Map<string, McpServerStatus>();

  // Store original config per server for reconnection
  private serverConfigs = new Map<string, any>();

  // The config the servers were last (re)connected from, and the connection round in
  // flight, so that a worker's start-up warm-up and its first task share one round.
  private currentConfigStr: string | null = null;
  private round: Promise<void> | null = null;
  // Each server's config as applied (JSON), to reconnect only what changed.
  private appliedConfigs = new Map<string, string>();
  // The tools each server registered, to remove exactly those when it goes away.
  private serverTools = new Map<string, Set<string>>();
  // When each server was last retried / restarted, to keep a broken one from costing
  // every task a connection timeout.
  private lastRetryAt = new Map<string, number>();

  /**
   * Brings the MCP servers in line with `configStr` and returns once they are usable or
   * `waitMs` has passed (the round goes on in the background). A different config
   * touches only the servers that were added, removed or changed — the rest keep their
   * connection; the same config retries the servers that failed or timed out, at most
   * once a minute each. Called at worker start and on its heartbeat (waitMs 0) and
   * before every task.
   */
  async ensure(configStr: string, waitMs = 15_000): Promise<void> {
    const settle = (ms: number) => (this.round && ms > 0 ? Promise.race([this.round, new Promise<void>((r) => setTimeout(r, ms))]) : Promise.resolve());
    if (configStr !== this.currentConfigStr) {
      // Let a round that is still connecting finish first: closing under it leaves child processes behind.
      await settle(Math.max(waitMs, 15_000));
      let parsed: any;
      try { parsed = JSON.parse(configStr); } catch { parsed = { mcpServers: {} }; }
      const next = new Map<string, string>();
      for (const [name, cfg] of Object.entries<any>(parsed?.mcpServers ?? {})) next.set(name, JSON.stringify(cfg ?? {}));
      for (const name of [...this.appliedConfigs.keys()]) {
        if (next.get(name) !== this.appliedConfigs.get(name)) await this.disconnectServer(name);
      }
      const changed: Record<string, any> = {};
      for (const [name, json] of next) if (this.appliedConfigs.get(name) !== json) changed[name] = JSON.parse(json);
      this.appliedConfigs = next;
      this.currentConfigStr = configStr;
      const names = Object.keys(changed);
      if (names.length) {
        console.log(`[MCP] Connecting ${names.length} server(s): ${names.join(', ')}`);
        this.startRound(this.connectServers({ mcpServers: changed }));
      }
    } else if (!this.round) {
      this.startRound(this.retryFailed());
    }
    await settle(waitMs);
  }

  /** Closes one server and forgets its tools and status. */
  private async disconnectServer(serverName: string): Promise<void> {
    killTransport(this.transports.get(serverName));
    try { await this.clients.get(serverName)?.close(); } catch (_) {}
    this.clients.delete(serverName);
    this.transports.delete(serverName);
    for (const toolName of this.serverTools.get(serverName) ?? []) this.mcpTools.delete(toolName);
    this.serverTools.delete(serverName);
    this.serverStatuses.delete(serverName);
    this.serverConfigs.delete(serverName);
    this.lastRetryAt.delete(serverName);
  }

  private startRound(work: Promise<unknown>): void {
    const p: Promise<void> = work.then(() => undefined, (e: any) => { console.error(`[MCP] connection round failed: ${e?.message ?? e}`); })
      .finally(() => { if (this.round === p) this.round = null; });
    this.round = p;
  }

  /** Reconnects the servers left in `failed` / `timeout`, each at most once per RETRY_COOLDOWN_MS. */
  async retryFailed(): Promise<number> {
    const now = Date.now();
    const due = [...this.serverStatuses.values()].filter((st) =>
      (st.state === 'failed' || st.state === 'timeout') && this.serverConfigs.has(st.name)
      && now - (this.lastRetryAt.get(st.name) ?? 0) >= (this.opts.retryCooldownMs ?? RETRY_COOLDOWN_MS));
    if (!due.length) return 0;
    for (const st of due) this.lastRetryAt.set(st.name, now);
    console.log(`[MCP] Retrying ${due.length} server(s) that did not connect: ${due.map((d) => d.name).join(', ')}`);
    await Promise.allSettled(due.map((st) => this.reconnectServer(st.name, this.serverConfigs.get(st.name))));
    return due.length;
  }

  async connectServers(mcpConfig: any) {
    if (!mcpConfig || !mcpConfig.mcpServers) return;
    // A remote server answers at once or not at all. A local one started through uvx, npx
    // or docker may have to download itself the first time (a minute is common), and
    // cutting that short kills the download, so it would never get to start: it gets
    // longer. Tasks do not wait for this (see ensure): they go on without the server.
    const REMOTE_TIMEOUT_MS = 10_000;
    const LOCAL_TIMEOUT_MS = 180_000;

    const connectionPromises = Object.entries<any>(mcpConfig.mcpServers).map(async ([serverName, config]) => {
      if (config.switch === "off") {
        console.log(`[MCP] Skipping disabled server: ${serverName}`);
        this.serverStatuses.set(serverName, {
          name: serverName,
          state: 'disconnected',
          toolCount: 0,
          transport: config.command ? 'stdio' : config.url ? 'sse' : 'unknown'
        });
        return;
      }

      // Store config for potential reconnection
      this.serverConfigs.set(serverName, config);

      // Mark as connecting
      this.serverStatuses.set(serverName, {
        name: serverName,
        state: 'connecting',
        toolCount: 0,
        transport: config.command ? 'stdio' : config.url ? 'sse' : 'unknown'
      });

      let transport: any = null;
      let transportKind: 'stdio' | 'sse' | 'http' = config.command ? 'stdio' : 'sse';
      try {
        await withTimeout((async () => {
          let client: Client;
          if (config.command) {
            console.log(`[MCP] Connecting to ${serverName} via STDIO (${config.command})...`);
            transport = new StdioClientTransport({
              command: config.command,
              args: config.args || [],
              env: { ...process.env, ...(config.env || {}) }
            });
            client = new Client({ name: "hydraops", version: "1.0.0" }, { capabilities: {} });
            await client.connect(transport);
          } else if (config.url) {
            // Remote servers: Streamable HTTP first (current spec), SSE as legacy fallback.
            // config.headers (e.g. Authorization) is forwarded on both transports.
            const httpOpts = config.headers ? { requestInit: { headers: config.headers } } : undefined;
            try {
              console.log(`[MCP] Connecting to ${serverName} via Streamable HTTP (${config.url})...`);
              transport = new StreamableHTTPClientTransport(new URL(config.url), httpOpts);
              client = new Client({ name: "hydraops", version: "1.0.0" }, { capabilities: {} });
              await client.connect(transport);
              transportKind = 'http';
            } catch (httpErr: any) {
              killTransport(transport);
              console.log(`[MCP] ${serverName}: Streamable HTTP failed (${httpErr?.message}) — falling back to SSE...`);
              transport = new SSEClientTransport(new URL(config.url), httpOpts as any);
              client = new Client({ name: "hydraops", version: "1.0.0" }, { capabilities: {} });
              await client.connect(transport);
              transportKind = 'sse';
            }
          } else {
            throw new Error(`Invalid configuration for ${serverName}: no command or url`);
          }

          this.clients.set(serverName, client);
          this.transports.set(serverName, transport);

          // Request tools from this MCP server
          const response: any = await client.request({ method: "tools/list" }, z.any());
          const tools = response?.tools || [];

          let registeredCount = 0;
          let unclassified = 0;
          const registered = new Set<string>();
          for (const t of tools) {
            const toolName = `${serverName.replace(/\s+/g, '_').toLowerCase()}_${t.name}`;
            const zodSchema = jsonSchemaToZod(t.inputSchema);
            const risk = classifyMcpTool(serverName, t.annotations, config.toolRisk?.[t.name]);
            if (risk.basis === 'unknown') unclassified++;
            registered.add(toolName);

            this.mcpTools.set(toolName, {
              name: toolName,
              description: `[From ${serverName}]: ${t.description || ''}`,
              schema: zodSchema,
              execute: this.createToolExecutor(serverName, t.name),
              // The config's own word on this tool, a known server, or the tool's MCP
              // annotations; worst case otherwise.
              risk,
            });
            registeredCount++;
            console.log(`[MCP] Registered tool: ${toolName}`);
          }

          this.serverTools.set(serverName, registered);

          // Mark as connected
          this.serverStatuses.set(serverName, {
            name: serverName,
            state: 'connected',
            toolCount: registeredCount,
            ...(unclassified ? { unclassified } : {}),
            connectedAt: new Date().toISOString(),
            transport: transportKind
          });

          console.log(`[MCP] ✅ ${serverName} connected — ${registeredCount} tools registered.`);
        })(), config.command ? LOCAL_TIMEOUT_MS : REMOTE_TIMEOUT_MS, `connection to ${serverName}`);
      } catch (err: any) {
        const isTimeout = err.message?.includes('Timeout');
        const state: McpServerState = isTimeout ? 'timeout' : 'failed';
        const errorMsg = err.message || 'Unknown error';

        console.error(`[MCP] ❌ Server ${serverName} ${state}: ${errorMsg}`);

        this.serverStatuses.set(serverName, {
          name: serverName,
          state,
          toolCount: 0,
          error: errorMsg,
          transport: config.command ? 'stdio' : config.url ? 'sse' : 'unknown'
        });

        // Kill the transport/child process to prevent zombies
        killTransport(transport);

        // Also remove from clients/transports if they were partially set
        this.clients.delete(serverName);
        this.transports.delete(serverName);
      }
    });

    // FIXED: Actually wait for all connections to settle
    const results = await Promise.allSettled(connectionPromises);
    const connected = [...this.serverStatuses.values()].filter(s => s.state === 'connected').length;
    const failed = [...this.serverStatuses.values()].filter(s => s.state === 'failed' || s.state === 'timeout').length;
    const disabled = [...this.serverStatuses.values()].filter(s => s.state === 'disconnected').length;

    console.log(`[MCP] Initialization complete: ${connected} connected, ${failed} failed, ${disabled} disabled. Total tools: ${this.mcpTools.size}`);
  }

  /**
   * Creates a tool executor with automatic error handling and reconnection
   */
  private createToolExecutor(serverName: string, toolOriginalName: string) {
    return async (args: any): Promise<string> => {
      console.log(`[MCP Tool Exec] Calling ${toolOriginalName} on ${serverName}...`);
      // Looked up per call: after a reconnection the same tool object talks to the new client.
      const client = this.clients.get(serverName);
      if (!client) {
        this.scheduleRestart(serverName, 'no live connection');
        return `Error executing MCP tool ${toolOriginalName}: ${serverName} is not connected right now (reconnecting); try again in a moment.`;
      }

      try {
        const timeoutMs = toolCallTimeoutMs(this.serverConfigs.get(serverName));
        const res: any = await withTimeout(
          client.request(
            { method: "tools/call", params: { name: toolOriginalName, arguments: args } },
            z.any(),
            // The SDK has its own limit per request (60 s by default): it follows ours.
            { timeout: timeoutMs }
          ),
          timeoutMs,
          `tool call ${toolOriginalName}`
        );

        const text = sanitizeMcpContent(res.content, toolOriginalName);
        // The server answered, but says it lost what IT talks to (Blender closed and
        // reopened, a browser gone): a fresh server process reconnects on start.
        if (DOWNSTREAM_LOST.test(text.slice(0, 400))) this.scheduleRestart(serverName, 'the server reports a lost connection');
        return res.isError ? `MCP Server Error: ${text}` : text;
      } catch (execErr: any) {
        const errMsg = execErr.message || 'Unknown execution error';
        console.error(`[MCP Tool Exec] ❌ ${toolOriginalName} on ${serverName} failed: ${errMsg}`);

        // Mark server as failed if connection is dead
        if (errMsg.includes('closed') || errMsg.includes('EPIPE') || errMsg.includes('killed') || errMsg.includes('disconnect')) {
          this.serverStatuses.set(serverName, {
            name: serverName,
            state: 'failed',
            toolCount: 0,
            error: `Connection lost: ${errMsg}`,
            transport: this.serverStatuses.get(serverName)?.transport || 'unknown'
          });

          // Attempt reconnection in background
          this.scheduleRestart(serverName, 'connection lost', 0);
        }

        return `Error executing MCP tool ${toolOriginalName}: ${errMsg}`;
      }
    };
  }

  /** Restarts one server in the background, at most once per `cooldownMs`. */
  private scheduleRestart(serverName: string, why: string, cooldownMs = this.opts.restartCooldownMs ?? RESTART_COOLDOWN_MS): void {
    const config = this.serverConfigs.get(serverName);
    if (!config) return;
    const now = Date.now();
    if (now - (this.lastRetryAt.get(serverName) ?? 0) < cooldownMs) return;
    this.lastRetryAt.set(serverName, now);
    console.log(`[MCP] Restarting ${serverName} (${why})...`);
    this.reconnectServer(serverName, config).catch(
      (e) => console.error(`[MCP] Reconnection for ${serverName} failed: ${e.message}`)
    );
  }

  /**
   * Reconnect a single server that has disconnected
   */
  private async reconnectServer(serverName: string, config: any): Promise<void> {
    // Clean up old connection
    const oldTransport = this.transports.get(serverName);
    killTransport(oldTransport);
    const oldClient = this.clients.get(serverName);
    try { await oldClient?.close(); } catch (_) {}
    this.clients.delete(serverName);
    this.transports.delete(serverName);

    // Remove old tools from this server
    for (const toolName of this.serverTools.get(serverName) ?? []) this.mcpTools.delete(toolName);
    this.serverTools.delete(serverName);

    // Reconnect as if it were a fresh config (single server)
    await this.connectServers({ mcpServers: { [serverName]: config } });
  }

  /**
   * Get the statuses of all known MCP servers
   */
  getStatuses(): McpServerStatus[] {
    return [...this.serverStatuses.values()];
  }

  async closeAll() {
    // Close transports first to kill child processes
    for (const [name, transport] of this.transports.entries()) {
      try {
        await transport.close();
      } catch (e) {
        killTransport(transport);
        console.error(`[MCP] Error cerrando transporte ${name}`, e);
      }
    }
    this.transports.clear();

    for (const [name, client] of this.clients.entries()) {
      try {
        await client.close();
      } catch (e) {
        console.error(`[MCP] Error cerrando client ${name}`, e);
      }
    }
    this.clients.clear();
    this.mcpTools.clear();
    this.serverStatuses.clear();
    this.serverConfigs.clear();
    this.lastRetryAt.clear();
    this.appliedConfigs.clear();
    this.serverTools.clear();
    this.currentConfigStr = null;
  }
}
